name: pikpak_auto_invite
on:
  workflow_dispatch: # 允许手动触发工作流
  push:
    branches: [ main ]
    paths:
      - '**'
      - '!.gitignore'
      - '!README.md'
  schedule:
  # 每天早上8点30执行一次 (08:30 Asia/Shanghai)
  - cron: '30 0 * * *'
  # 每天晚上6点30执行一次 (18:30 Asia/Shanghai)
  - cron: '30 10 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set Time
        run: sudo timedatectl set-timezone 'Asia/Shanghai'
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - run: pip install -r requirements.txt
      - name: Run
        env:
          INVITE_CODE: ${{secrets.INVITE_CODE}}
          PUSHPLUS_TOKEN: ${{secrets.PUSHPLUS_TOKEN}}
        run: python run.py
